### ISSUE TITLE
Go through kubebuilder or K8s native API 

### ISSUE THREAD

**Issue by merlintang** [kubeflow/xgboost-operator#13]
Hi All 

When I implement the XGB operator, I am wondering which way is better to implement the interface of kubeflow common?  

I found Pytorch Operator or TF operator do not use KubeBuilder. thus, we do not use KubeBuilder for XGB operator similar as the Pytorch and TF operator? 

thanks 

Mingjie

**Comment by merlintang** [comment]
@terrytangyuan @johnugeorge can you give some suggestions ?

**Comment by terrytangyuan** [comment]
We discussed using kubebuilder here: https://github.com/kubeflow/common/issues/7. It’s a good idea but there will be separate efforts to rewrite all the logic and tests so maybe we should do it later.

**Comment by richardsliu** [comment]
We do not use Kubebuilder for TFJob and PytorchJob because those are already written, and rewriting all the logic will take a lot of time with little benefit.

But for new operators, using Kubebuilder may save a lot of effort. I would be interested in seeing how this works with the common interface. If it works well, we can publish a tutorial on how to build your own Kubeflow operator in simple steps.

**Comment by merlintang** [comment]
We have agreed to move on xgb operator based on kubebuilder + kubeflow common. Thanks for your advice @terrytangyuan  @richardsliu
