### ISSUE TITLE
Support for xgboost-jvm-package with Spark on Kubeflow

### ISSUE THREAD

**Issue by cyzhangchenya** [kubeflow/xgboost-operator#40]
As mentioned on the homepage, "Distributed XGBoost job is trained by synchronizing different worker status via tne Rabit of XGBoost", to double confirm:
--> The xgboost-operator is not leveraging xgboost-jvm-package with Spark for distributed training in this case.
--> There is no requirement of supporting Spark on the Kubernetes cluster used (if we use a customized one).

btw. Is there any plan of supporting xgboost-jvm-package with Spark on Kubeflow?

**Comment by merlintang** [comment]
--> The xgboost-operator is not leveraging xgboost-jvm-package with Spark for distributed training in this case.
--> There is no requirement of supporting Spark on the Kubernetes cluster used (if we use a customized one).

this is not related to spark, since the distributed training is based on rabit rather than spark.

xgboost-jvm-package is based on spark, thus you can use spark over k8s to run it.

**Comment by merlintang** [comment]
close this one.
